//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore.WebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int MessageId { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
        public Nullable<int> SenderId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
