//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore.WebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public int ProductId { get; set; }
        public string Username { get; set; }
        public string Comment { get; set; }
        public int Rating { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> AppUserUserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Product Product { get; set; }
    }
}
