//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore.WebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warranty
    {
        public int WarrantyId { get; set; }
        public string SerialNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string IssueDescription { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public string Status { get; set; }
        public string TechnicianNote { get; set; }
    }
}
